---
name: Manual
on:
 workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/reusable/reusable_test-python.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable/reusable_build-push.yml
    with:
      name: '${{ github.repository }}'
      tags: '${{ github.ref_name }}'
