---
name: Build & Tag Image on PR
'on':
  pull_request:
    branches:
    - develop
    - main
    - master
    types:
    - closed
    - edited
    - opened
    - ready_for_review
    - reopened
    - synchronize
    - workflow_dispatch
jobs:
  run_build_and_push:
    uses: ./.github/workflows/build_and_push_image.yml
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
<<<<<<< HEAD

  tag_on_merge:
    uses: ./.github/workflows/tag_on_merge.yml
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}      
=======
>>>>>>> 5ff5a09fd03376e6bcd4497de729c4d18edf2bdd
